# Input/Output paths
input:
  sample_sheet: "resources/test_data/sample_sheet.csv"

# Output file paths
output:
  prefix: "test_data_virgo2"
  results_dir: "results"

# Virgo2 paths
virgo2:
  script_dir: "resources/VIRGO2_20250507"
  main_script: "VIRGO2.py"
  database_dir: "resources/VIRGO2_20250507"
  accessory_scripts:
    add_length: "Accessory_scripts/VIRGO2_add_length_taxa.py"
    relative_abundance: "Accessory_scripts/VIRGO2_calc_species_comp_glcorr.py"

# Resource configurations
resources:
  virgo2:
    threads: 8
    mem_mb: 32000 # Base memory allocation in MB
    mem_increment: 16000 # Additional memory to add per retry in MB
    runtime: "12h"
    partition: "short"
  other:
    mem_mb: 200000
    runtime: "12h"
    partition: "short"
  db_setup:
    threads: 12
    mem_mb: 64000
    runtime: "12h"
    partition: "short" 